<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAekIxN2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAekIxN2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAekIxN2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAekIxN2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAekIxN2\App_KernelDevDebugContainer([
    'container.build_hash' => 'AekIxN2',
    'container.build_id' => '9392aea8',
    'container.build_time' => 1590277270,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAekIxN2');
